version: '3.9'

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566" # LocalStack services endpoint
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range 
      - "8000:8000" # DynamoDB port

    environment:
      - SERVICES=s3,sqs,sns,dynamodb,lambda
      - DEBUG=1
      - PERSISTENCE=/tmp/localstack/data
      - LOCALSTACK_HOST=localstack # Updated variable name
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=localstack  
      - AWS_SECRET_ACCESS_KEY=localstack
      - APP_ENV=dev

    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./scripts/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh"  # ready hook

    networks:
      - localstack_network

networks:
  localstack_network:
    driver: bridge
