version: '3.9'
services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack_local
    ports:
      - "4566:4566" # Map Localstack's services to localhost
    environment:
      - SERVICES=sns,sqs # Enable SNS and SQS services
      - DEBUG=1 # Enable debugging for Localstack
      - DATA_DIR=/tmp/localstack/data # Set a data directory
    volumes:
      - ./localstack:/tmp/localstack # Mount a volume for persistence
    networks:
      - localstack_network

networks:
  localstack_network: